"""
Django settings for batimentRenovation project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

"""Settings Django sécurisés — les valeurs sensibles viennent des variables d'environnement."""

from pathlib import Path
import os

EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
DEFAULT_FROM_EMAIL = "no-reply@mon-site.com"
NOTIFY_EMAIL = "admin@mon-site.com"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# --- MULTI-REPO: Chemins vers le frontend (web-mvt/ui) ---
# Dans la structure multi-repo, templates/ et static/ sont dans le repo web-mvt/ui/
# On cherche le repo web-mvt au même niveau que backend/
_MULTI_REPO_ROOT = BASE_DIR.parent  # multi-repo-target/
_WEB_MVT_UI = _MULTI_REPO_ROOT / "web-mvt" / "ui"

# Fallback: si web-mvt/ui n'existe pas, on utilise les chemins locaux (monorepo)
if _WEB_MVT_UI.exists():
    FRONTEND_TEMPLATES_DIR = _WEB_MVT_UI / "templates"
    FRONTEND_STATIC_DIR = _WEB_MVT_UI / "static"
else:
    FRONTEND_TEMPLATES_DIR = BASE_DIR / "templates"
    FRONTEND_STATIC_DIR = BASE_DIR / "static"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-wup8kt1sqbu$ge$m+d%@u*y(k3qt(ic!7y1=lr-l)&sihg2t+q",  # fallback dev uniquement
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("DJANGO_DEBUG", "True") == "True"

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")

AUTH_USER_MODEL = "batimentRenovation.User"
LOGIN_URL = "login"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "batimentRenovation",
    "data",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "batimentRenovation.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [str(FRONTEND_TEMPLATES_DIR)],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "batimentRenovation.context_processors.site_contact",
            ],
        },
    },
]

WSGI_APPLICATION = "batimentRenovation.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []

if not DEBUG:
    AUTH_PASSWORD_VALIDATORS = [
        {
            "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
        },
        {
            "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
        },
    ]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
STATICFILES_DIRS = [
    FRONTEND_STATIC_DIR,
    FRONTEND_TEMPLATES_DIR,
]

"""AUTHENTICATION_BACKENDS = [
    'batimentRenovation.backends.EmailBackend',  # ← Ton backend
    'django.contrib.auth.backends.ModelBackend',
]
"""
